sudo: required
services:
- docker
language: bash
script:
# build image
- docker build -t andrevs/onedrive .
# test image
# - docker run spanghf37/knxd uname -a
## push image
- docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
- docker tag andrevs/onedrive andrevs/onedrive:latest
- docker push andrevs/onedrive:latest
